# docker-compose.yml
# runs both the express app and postgres database in the same space


version: "3"

services:
    db:
        image: postgres:12
        environment:
            - POSTGRES_DB=blog-db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    app:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - ./app/src:/app/src
        ports:
            - "8000:8000"
        depends_on:
            - db
        environment: 
            - POSTGRES_DB=blog-db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_HOST=db